### ISSUE TITLE
Error when "(" shows in URL

### ISSUE THREAD

**Issue by johnroyer** [tuxfoo/lbry-seedit#22]
I got an error when running `lbry-seedit.py`:

```
lbry://@zeroplex#8/Treasures!!-(Future-Stream)---Violin#7
/bin/sh: 1: Syntax error: "(" unexpected
```

LBRY URL is the same above. Is it kind of escaping problem ?

Thanks

**Comment by tuxfoo** [comment]
Have not come across any claims with those characters, thanks for alerting me of this.

You are correct and it is something I should have thought of; it is a escaping problem. 
Need to put the claim URI between ' character to escape it as it is accepted by both bash and the lbry api

For now a possible fix is to change the syscall in lbry-seedit.py
 
```
 subprocess.call("lbrynet get " + item["canonical_url"], shell=True)
```
to
```
subprocess.call("lbrynet get \'" + item["canonical_url"] + "\'", shell=True)
```

I will roll it out in the next update.

Cheers.

**Comment by tuxfoo** [comment]
pushed it to the dev branch 
https://github.com/tuxfoo/lbry-seedit/commit/f1b5e21c45a416484676aec929ebd41e043b77d1

**Comment by johnroyer** [comment]
I build and run again on f1b5e21: 

```
lbry://@zeroplex#8/Treasures!!-(Future-Stream)---Violin#7
{
  "added_on": 1608958089,
  "blobs_completed": 1,
  "blobs_in_stream": 10,
....
```

Every thing goes well.

----

Thanks for super fast reply and fix!
